language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
 - chmod +x ./baseCitizens/data/startup.sh
before_script:
- ./baseCitizens/data/startup.sh
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
